version: '3.8'

services:
  # AI Chatbot Backend
  chatbot-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ai-chatbot-api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MOCK_MODE=true
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - chatbot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: chatbot-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./advanced-frontend.html:/usr/share/nginx/html/index.html:ro
      - ./simple-frontend.html:/usr/share/nginx/html/simple.html:ro
    depends_on:
      - chatbot-api
    restart: unless-stopped
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge

volumes:
  chatbot-logs:
    driver: local
